### ISSUE TITLE
`AssertionError: Missing render sensors in agent config: ['third_rgb_sensor']`

### ISSUE THREAD

**Issue by DiTo97** [facebookresearch/eai-vc#11]
Hi all,

I tried to run the [training script](https://github.com/facebookresearch/eai-vc/blob/main/cortexbench/habitat2_vc/run_rearrangement_vc.py) of the MobilePick task for a limited number of steps.

The training seems to have ended successfully and the TensorBoard dashboard is correctly populated (I am not logging on W&B). The issue in the title happens when evaluating the code using your suggested command:

```bash
python run_rearrangement_vc.py model=vc1_vitb WANDB.run_name=<same_run_name_as_train> habitat_baselines.num_environments=10 hydra/launcher=slurm_eval_base RUN_TYPE=eval -m
```

I have also tried to mimic the configuration overrides that I used for training, but that error keeps happening. The PR [#959](https://github.com/facebookresearch/habitat-lab/pull/959) on `habitat-baselines` seems to have solved something related to `third_rgb_sensor`, but I am not sure if the two are related.

How could I solve the issue?

**Comment by DiTo97** [comment]
Up, @mathfac.

I'm sorry to bother you, but we would really like to experiment with MobilePick policies and that issue is a big roadblock for us

**Comment by ykarmesh** [comment]
@SergioArnaud

**Comment by SergioArnaud** [comment]
Sorry for the late response, the following needs to be added to the evaluation command

`habitat/simulator/agents@habitat.simulator.agents.main_agent=rgb_head_agent_vis`

**Comment by DiTo97** [comment]
@marino-multipla

**Comment by xwen99** [comment]
Hi @DiTo97, how did you resolve this issue? I added that to the evaluation command but the same error still exists...

**Comment by xwen99** [comment]
My temporary workaround is commenting out the following config as the error seems to be raised by a [visualization logic](https://github.com/mathfac/habitat-lab/blob/9e5731b444fd0648322ca39b2396d941a072adbf/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py#L962-L976), which is unnecessary. https://github.com/facebookresearch/eai-vc/blob/76fe35e87b1937168f1ec4b236e863451883eaf3/cortexbench/habitat2_vc/configs/experiments/rl_skill.yaml#L35-L36

Also, `habitat_baselines.load_resume_state_config` should be set to False to make evaluation configs valid, otherwise they will be overridden by training configs.
